### ISSUE TITLE
Salt password

### ISSUE THREAD

**Issue by Timo614** [big-neon/bn-db#40]
We're not currently salting the passwords we're hashing worth adding though.

https://github.com/big-neon/bn-db/blob/master/src/models/users.rs#L67

**Comment by CjS77** [comment]
For sure. Additionally, Hashing for password verification should also
happen on the client side, otherwise the server can be dossed.

**Comment by philipr-za** [comment]
The password is being salted during the hashing process. The Argon2i library stores the salt as part of the hash string. I confirmed by adding two users with the same password and the hash strings are different.

**Comment by Timo614** [comment]
Ah yeah it looks like if one isn't provided to that method we do generate one: https://github.com/big-neon/bn-db/blob/master/src/utils/passwords.rs#L17
