### ISSUE TITLE
User roles and permissions

### ISSUE THREAD

**Issue by CjS77** [big-neon/bn-db#5]
* Define roles according to user stories 
* Define `users` table
* Define roles for admin, org-manager, org-admin, user, guest
* Admin - has full rights to all tables on platform
* OrgManager - Can CRUD any tables with rows belonging to their Org; Can READ rows on ORG table where they are owner; Can UPATE some columns on Org table where they are owner; Can make other users OrgAdmins; Can READ org history
* OrgAdmin - Can CRUD event tables belonging to their Org; can READ org history
* User (Authenticated user) - Can update their row in users; can READ transaction history;

**Comment by zmelamed** [comment]
@CjS77 I've created this PR with some more information regarding organization user roles: https://github.com/big-neon/docs/pull/9
